config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"


  scope '/learning' do
    get '/', to: 'learning#index', as: 'learning'
    get '/notes', to: 'notes#index', as: 'learning_notes'
    get '/structure', to: 'learning#structure', as: 'learning_structure'
    get '/dump', to: 'learning#dump', as: 'learning_dump'
    get '/assignments', to: 'assignments#index', as: 'interview_assignments'
    post '/assignments', to: 'assignments#create' # если нужен
    get '/tools', to: 'tools#index', as: 'learning_tools'
    get '/stack', to: 'positions#index', as: 'learning_stack'
    get '/remarks', to: 'remarks#index', as: 'learning_remarks'
  end

  get '/software-dev', to: 'software_dev#index', as: 'software_dev'
  get '/software-test', to: 'software_test#index', as: 'software_test' # as: это в каком виде прописывать path

  resources :positions do
    resources :sections do
      resources :articles do
        resources :practical_tasks
      end
    end
    resources :tool_sections do
      resources :tools do
        resources :posts
        resources :features
      end
    end
  end
  

  resources :assignments

  resources :notes

  resources :remarks

  resources :flows

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :section
  has_many :practical_tasks

  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 10 }
end

app/models/assignment.rb
class Assignment < ApplicationRecord
end

app/models/feature.rb
class Feature < ApplicationRecord
  belongs_to :tool
end

app/models/flow.rb
class Flow < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/position.rb
class Position < ApplicationRecord
    has_many :sections
    has_many :tool_sections
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :tool
end

app/models/practical_task.rb
class PracticalTask < ApplicationRecord
  belongs_to :article
end

app/models/remark.rb
class Remark < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
    belongs_to :position
    
    has_many :articles, dependent: :destroy
end

app/models/tool.rb
class Tool < ApplicationRecord
    belongs_to :tool_section

    has_many :posts
    has_many :features

    validates :title, presence: true
end

app/models/tool_section.rb
class ToolSection < ApplicationRecord
  belongs_to :position
  has_many :tools
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
                    format:     { with: VALID_EMAIL_REGEX }
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  
  before_action :set_position
  before_action :set_tool_section
  before_action :set_tool, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @tool = @tool_section.tools.build
  end

  def create
    @tool = @tool_section.tools.build(tool_params)
    if @tool.save
      redirect_to position_tool_section_tool_path(@position, @tool_section, @tool), notice: 'Статья успешно создана.'
    else
      render :new
    end
  end


  def edit
  end


  def update
    if @tool.update(tool_params)
      redirect_to position_tool_section_tool_path(@position, @tool_section, @tool), notice: 'Tool успешно обновлен.'
    else
      render :edit
    end
  end

 
  def destroy
    @tool.destroy
    redirect_to position_tool_section_path(@position, @tool_section), notice: 'Tool успешно удален.'
  end

  private

  def set_position
    @position = Position.find(params[:position_id])
  end

  # Установка раздела
  def set_tool_section
    @tool_section = ToolSection.find(params[:tool_section_id])
  end

  # Установка статьи
  def set_tool
    @tool = @tool_section.tools.find(params[:id])
  end

  # Strong parameters
  def tool_params
    params.require(:tool).permit(:title, :description, :documentation_link, :logo_path, :platform, :history, :tool_section_id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/flows_helper.rb
module FlowsHelper
end

app/helpers/learning_helper.rb
module LearningHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/remarks_helper.rb
module RemarksHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tools/edit.html.erb
<% provide(:title, 'Edit a tool')%>

<%= render 'layouts/tools/form_edit' %>

app/views/tools/new.html.erb
<% provide(:title, 'New tool')%>

<%= render 'layouts/tools/form_new' %>

app/views/tools/show.html.erb
<% provide(:title, @tool.title)%>

<div class='objects-navigation'>
    <%= link_to '[back]', position_tool_section_path(@tool.tool_section.position, @tool.tool_section) %>
    <%= link_to '[edit]', edit_position_tool_section_tool_path(@tool.tool_section.position, @tool.tool_section, @tool) %>
    <%= link_to '[delete]', position_tool_section_tool_path(@tool.tool_section.position, @tool.tool_section, @tool), method: :delete, data: { confirm: 'Вы уверены?' } %>
</div>

<div class='content-div'>

    <div class="left-side-navbar">
        <div class='tool-card'>
            <div class='tool-card-logo-name'>
                <%= image_tag(@tool.logo_path, class: "tool-logo") %>
                <h2 class="tool-title"><%= @tool.title %></h2>
            </div>

            <div class='tool-card-category-link'>
                <p><%= @tool_section.title %></p>
                <p><%= @tool.platform %></p>
                <a href="<%= @tool.documentation_link %>" target='_blank'>Официальная документация</a>
            </div>
        </div>

    </div>

    <div class='description'>
        <div class='description-block'>
            <h4 class='description-block-title'>Статьи</h4>
            <%= link_to '[add article]', new_position_tool_section_tool_post_path(@tool.tool_section.position, @tool.tool_section, @tool, @post) %>
                <ul class='tool-posts-list'>
                    <% @tool.posts.each do |post| %>
                    <li><%= link_to post.title, position_tool_section_tool_post_path(@tool.tool_section.position, @tool.tool_section, @tool, post) %></li>
                    <% end %>
                </ul>
        </div>

        <div class='description-block'>    
            <h4 class='description-block-title'>Описание</h4>
            <p><%= @tool.description.html_safe %></p>
        </div>

        <div class='description-block'>    
            <h4 class='description-block-title'>Ключевая функциональность</h4>
            <%= link_to '[add feature]', new_position_tool_section_tool_feature_path(@tool.tool_section.position,@tool.tool_section, @tool, @feature) %>
            <ul>
                <% @tool.features.each do |feature| %>
                  <li><%= link_to feature.description, position_tool_section_tool_feature_path(@position, @tool_section, @tool, feature) %></li>
                <% end %>
            </ul>
        </div>

        <div class='description-block'>
            <h4 class='description-block-title'>История</h4>
            <p><%= @tool.history.html_safe %></p>
        </div>
    </div>

</div>