config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"


  scope '/learning' do
    get '/', to: 'learning#index', as: 'learning'
    get '/notes', to: 'notes#index', as: 'learning_notes'
    get '/structure', to: 'learning#structure', as: 'learning_structure'
    get '/dump', to: 'learning#dump', as: 'learning_dump'
    get '/assignments', to: 'assignments#index', as: 'interview_assignments'
    post '/assignments', to: 'assignments#create' # если нужен
    get '/tools', to: 'tools#index', as: 'learning_tools'
    get '/stack', to: 'positions#index', as: 'learning_stack'
    get '/remarks', to: 'remarks#index', as: 'learning_remarks'
  end

  get '/software-dev', to: 'software_dev#index', as: 'software_dev'
  get '/software-test', to: 'software_test#index', as: 'software_test' # as: это в каком виде прописывать path

  resources :positions do
    resources :sections do
      resources :articles do
        resources :practical_tasks
      end
    end
    resources :tool_sections do
      resources :tools do
        resources :posts
        resources :features
      end
    end
  end
  

  resources :assignments

  resources :notes

  resources :remarks

  resources :flows

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :section
  has_many :practical_tasks

  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 10 }
end

app/models/assignment.rb
class Assignment < ApplicationRecord
end

app/models/feature.rb
class Feature < ApplicationRecord
  belongs_to :tool
end

app/models/flow.rb
class Flow < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/position.rb
class Position < ApplicationRecord
    has_many :sections
    has_many :tool_sections
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :tool
end

app/models/practical_task.rb
class PracticalTask < ApplicationRecord
  belongs_to :article
end

app/models/remark.rb
class Remark < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
    belongs_to :position
    
    has_many :articles, dependent: :destroy
end

app/models/tool.rb
class Tool < ApplicationRecord
    belongs_to :tool_section

    has_many :posts
    has_many :features

    validates :title, presence: true
end

app/models/tool_section.rb
class ToolSection < ApplicationRecord
  belongs_to :position
  has_many :tools
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
                    format:     { with: VALID_EMAIL_REGEX }
end

app/controllers/learning_controller.rb
class LearningController < ApplicationController

    def index
    end
    
    def structure
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/flows_helper.rb
module FlowsHelper
end

app/helpers/learning_helper.rb
module LearningHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/remarks_helper.rb
module RemarksHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/learning/index.html.erb
<% provide(:title, "Learning") %>
<h1>Learning Main</h1>

<div class='index-div'>
  <ul class='index-list'>
    <li><%= link_to "Software Dev", software_dev_path %></li>
    <li><%= link_to "Software Testing", software_test_path %></li>
    <li><%= link_to "Flows", flows_path %></li>
  </ul>
</div>

app/views/learning/structure.html.erb
<% provide(:title, 'Структура собеседования') %>
<h1>Структура собеседования на позицию Junior QA Engineer</h1>

<div class='article-content'>
    <p>
        Что такое тестирование?
        Откуда ты возьмешь ожидаемое поведение?
        Цели тестирования
        Чем отличается верификация от валидации?
        Виды тестирования
        Техники тестирования
        Тестовая документация
        Критерии выбора между чеклистом и тест-кейсом
        Жизненный цикл бага
        Тест-дизайн
        Техники тест-дизайна
        Виды приложений. Какие особенности работы и тестирования веб приложений?
        Методологии разработки ПО (SDLC)
        Чем отличается Scrum и Kanban?
        В чем разница между Severity и Priority?
        Что такое SQL?
        Основные запросы в SQL
        Что такое REST и SOAP? В чем разница?
        Что происходит когда ты делаешь запрос в браузере?
        Что такое HTTP и HTTPS?
        Основные запросы HTTP
        Структура HTTP запроса
        Структура HTTP ответа
        Статус коды
        Что такое SSL?
        Что такое TCP/IP?
        В чем разница между Cache и Cookie?
        Какие операционные системы ты знаешь?
        Основные команды терминала Unix
        Что такое Git?
        Основные команды Git
        Что такое Postman?
        
    </p>
</div>