config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"


  scope '/learning' do
    get '/', to: 'learning#index', as: 'learning'
    get '/notes', to: 'notes#index', as: 'learning_notes'
    get '/structure', to: 'learning#structure', as: 'learning_structure'
    get '/dump', to: 'learning#dump', as: 'learning_dump'
    get '/assignments', to: 'assignments#index', as: 'interview_assignments'
    post '/assignments', to: 'assignments#create' # если нужен
    get '/tools', to: 'tools#index', as: 'learning_tools'
    get '/stack', to: 'positions#index', as: 'learning_stack'
    get '/remarks', to: 'remarks#index', as: 'learning_remarks'
  end

  get '/software-dev', to: 'software_dev#index', as: 'software_dev'
  get '/software-test', to: 'software_test#index', as: 'software_test' # as: это в каком виде прописывать path

  resources :positions do
    resources :sections do
      resources :articles do
        resources :practical_tasks
      end
    end
    resources :tool_sections do
      resources :tools do
        resources :posts
        resources :features
      end
    end
  end
  

  resources :assignments

  resources :notes

  resources :remarks

  resources :flows

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :section
  has_many :practical_tasks

  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 10 }
end

app/models/assignment.rb
class Assignment < ApplicationRecord
end

app/models/feature.rb
class Feature < ApplicationRecord
  belongs_to :tool
end

app/models/flow.rb
class Flow < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/position.rb
class Position < ApplicationRecord
    has_many :sections
    has_many :tool_sections
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :tool
end

app/models/practical_task.rb
class PracticalTask < ApplicationRecord
  belongs_to :article
end

app/models/remark.rb
class Remark < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
    belongs_to :position
    
    has_many :articles, dependent: :destroy
end

app/models/tool.rb
class Tool < ApplicationRecord
    belongs_to :tool_section

    has_many :posts
    has_many :features

    validates :title, presence: true
end

app/models/tool_section.rb
class ToolSection < ApplicationRecord
  belongs_to :position
  has_many :tools
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
                    format:     { with: VALID_EMAIL_REGEX }
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :set_note, only: [:show, :edit, :update, :destroy]
  
    # GET /notes
    def index
      @notes = Note.all
    end
  
    # GET /notes/:id
    def show
    end
  
    # GET /notes/new
    def new
      @note = Note.new
    end
  
    # POST /notes
    def create
      @note = Note.new(note_params)
  
      if @note.save
        redirect_to @note, notice: 'Note was successfully created.'
      else
        render :new
      end
    end
  
    # GET /notes/:id/edit
    def edit
    end
  
    # PATCH/PUT /notes/:id
    def update
      if @note.update(note_params)
        redirect_to @note, notice: 'Note was successfully updated.'
      else
        render :edit
      end
    end
  
    # DELETE /notes/:id
    def destroy
      @note.destroy
      redirect_to notes_url, notice: 'Note was successfully destroyed.'
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_note
        @note = Note.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def note_params
        params.require(:note).permit(:title, :content)
        # Замените :title и :content на реальные атрибуты вашей модели Note
      end
  end
  

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/flows_helper.rb
module FlowsHelper
end

app/helpers/learning_helper.rb
module LearningHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/remarks_helper.rb
module RemarksHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/notes/_form_edit.html.erb
<%= form_with(model: @note, local: true) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "single-line-input-area" %>
  </div>

  <div>
    <%= form.text_area :content, class: "tinymce" %>
    <%= tinymce %>
  </div>

  <div class="form-actions">
    <%= form.submit "Сохранить изменения" %>
  </div>

<% end %>

<%= link_to 'Отмена', note_path(@note) %>

app/views/layouts/notes/_form_new.html.erb
<%= form_with(model: @note, local: true) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "single-line-input-area" %>
  </div>

  <div>
    <%= form.text_area :content, class: "tinymce" %>
    <%= tinymce %>
  </div>

  <div class="form-actions">
    <%= form.submit "Сохранить изменения" %>
  </div>

<% end %>

<%= link_to 'Отмена', interview_notes_path %>

app/views/notes/edit.html.erb
<% provide(:title, @note.title) %>

<%= link_to '[back]', note_path(@note) %>

<h1><%= @note.title %></h1>

<%= render 'layouts/notes/form_edit' %>

app/views/notes/index.html.erb
<% provide(:title, 'Notes') %>

<%= link_to '[back]', interview_path %>
<%= link_to '[new note]', new_note_path(@note) %>


<h1>Notes</h1>

<ul class = 'index-list'>
    <% @notes.each do |note| %>
        <li>
            <%= link_to note.title, note_path(note) %>
        </li>
    <% end %>
</ul>

app/views/notes/new.html.erb
<% provide(:title, 'New note') %>

<%= link_to '[back]', interview_notes_path %>

<%= render 'layouts/notes/form_new' %>

app/views/notes/show.html.erb
<% provide(:title, @note.title)%>

<%= link_to '[back]', interview_notes_path %>
<%= link_to '[edit]', edit_note_path(@note) %>
<%= link_to '[delete]', note_path(@note), method: :delete, data: { confirm: 'Вы уверены?' } %>

<div class="notes__content__div">
    <h1><%= @note.title %></h1>
    <h6 class='created-at'><%= @note.created_at.strftime("%B %d, %Y") %></h6>

    <p>
        <%= @note.content.html_safe %>
    </p>
</div>