config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"


  scope '/learning' do
    get '/', to: 'learning#index', as: 'learning'
    get '/notes', to: 'notes#index', as: 'learning_notes'
    get '/structure', to: 'learning#structure', as: 'learning_structure'
    get '/dump', to: 'learning#dump', as: 'learning_dump'
    get '/assignments', to: 'assignments#index', as: 'interview_assignments'
    post '/assignments', to: 'assignments#create' # если нужен
    get '/tools', to: 'tools#index', as: 'learning_tools'
    get '/stack', to: 'positions#index', as: 'learning_stack'
    get '/remarks', to: 'remarks#index', as: 'learning_remarks'
  end

  get '/software-dev', to: 'software_dev#index', as: 'software_dev'
  get '/software-test', to: 'software_test#index', as: 'software_test' # as: это в каком виде прописывать path

  resources :positions do
    resources :sections do
      resources :articles do
        resources :practical_tasks
      end
    end
    resources :tool_sections do
      resources :tools do
        resources :posts
        resources :features
      end
    end
  end
  

  resources :assignments

  resources :notes

  resources :remarks

  resources :flows

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :section
  has_many :practical_tasks

  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 10 }
end

app/models/assignment.rb
class Assignment < ApplicationRecord
end

app/models/feature.rb
class Feature < ApplicationRecord
  belongs_to :tool
end

app/models/flow.rb
class Flow < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/position.rb
class Position < ApplicationRecord
    has_many :sections
    has_many :tool_sections
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :tool
end

app/models/practical_task.rb
class PracticalTask < ApplicationRecord
  belongs_to :article
end

app/models/remark.rb
class Remark < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
    belongs_to :position
    
    has_many :articles, dependent: :destroy
end

app/models/tool.rb
class Tool < ApplicationRecord
    belongs_to :tool_section

    has_many :posts
    has_many :features

    validates :title, presence: true
end

app/models/tool_section.rb
class ToolSection < ApplicationRecord
  belongs_to :position
  has_many :tools
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
                    format:     { with: VALID_EMAIL_REGEX }
end

app/controllers/remarks_controller.rb
class RemarksController < ApplicationController
  before_action :set_remark, only: [:show, :edit, :update, :destroy]

  def index
    @remarks = Remark.all
  end

  def show
  end

  def new
    @remark = Remark.new
  end

  # POST /notes
  def create
    @remark = Remark.new(remark_params)

    if @remark.save
      redirect_to @remark, notice: 'Remark was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @remark.update(remark_params)
      redirect_to @remark, notice: 'Remark was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @remark.destroy
    redirect_to interview_remarks_url, notice: 'Remark was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_remark
      @remark = Remark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def remark_params
      params.require(:remark).permit(:title, :content)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/flows_helper.rb
module FlowsHelper
end

app/helpers/learning_helper.rb
module LearningHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/remarks_helper.rb
module RemarksHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/remarks/_form_edit.html.erb
<%= form_with(model: @remark, local: true) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "single-line-input-area" %>
  </div>

  <div>
    <%= form.text_area :content, class: "tinymce" %>
    <%= tinymce %>
  </div>

  <div class="form-actions">
    <%= form.submit "Сохранить изменения" %>
  </div>

<% end %>

app/views/layouts/remarks/_form_new.html.erb
<%= form_with(model: @remark, local: true) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "single-line-input-area" %>
  </div>

  <div>
    <%= form.text_area :content, class: "tinymce" %>
    <%= tinymce %>
  </div>

  <div class="form-actions">
    <%= form.submit "Сохранить изменения" %>
  </div>

<% end %>

app/views/remarks/edit.html.erb
<% provide(:title, 'Edit remark')%>

<h1>Edit remark</h1>

<%= render 'layouts/remarks/form_edit' %>

app/views/remarks/index.html.erb
<% provide(:title, 'Ресурсы')%>

<%= link_to 'back', interview_path %>
<%= link_to "add remark", new_remark_path(@remark) %>

<h1>Полезные ресурсы</h1>


<div class='index-div'>

    <ul class='index-list'>
        <% @remarks.each do |remark| %>
            <li>
                <%= link_to remark.title, remark_path(remark) %>
            </li>
        <% end %>
    </ul>
</div>

app/views/remarks/new.html.erb
<% provide(:title, 'New remark')%>

<h1>New remark</h1>

<%= render 'layouts/remarks/form_new' %>

app/views/remarks/show.html.erb
<% provide(:title, @remark.title) %>

<%= link_to '[back to all remarks]', interview_remarks_path %>
<%= link_to '[edit]', edit_remark_path(@remark) %>
<%= link_to '[delete]', remark_path(@remark), method: :delete, data: { confirm: 'Вы уверены?' } %>

<div class='article__div'>
    <h1 class='article__title'><%= @remark.title %></h1>
    <div class='article__text__div'>
      <p class='article__text'><%= @remark.content.html_safe %></p>
    </div>
</div>